### ISSUE TITLE
Details on rPi Connection

### ISSUE THREAD

**Issue by fia5000** [cschriel/Bekant-Desk#1]
Hi,
Is there any possibility to perhaps detail how you hooked up your rpi to the Bekant controller? Any photos or schematics you could perhaps share?

**Comment by cschriel** [comment]
I don't have a real schematic of any kind. I am basicly just emulating a button press using the raspberry pi, hardwiring the rPi GPIO's to the ribbon cable the pushbuttons are connected to. I messed up mine, but it does work without cutting the ribbon cable.

Orange	> J8 Header 12 (GPIO 1)
White	> J8 Header 11 (GPIO 0)
Black	> J8 Header 6 (Ground)

![rpi](https://user-images.githubusercontent.com/14190796/30006084-aa909600-90f0-11e7-8770-a0c11c8598ea.jpg)
![bekant controller](https://user-images.githubusercontent.com/14190796/30006083-aa900546-90f0-11e7-942b-b8a0156cdb08.jpg)
![j8header-b-plus-large](https://user-images.githubusercontent.com/14190796/30006085-aa92bba6-90f0-11e7-9502-d37227c67afe.png)

**Comment by fia5000** [comment]
@cschriel Thanks.
